---
label: Page
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- name: tags
  type: tag_list
  default: []
  label: tags
