name: Jekyll CI

on:
  schedule:
    - cron:  '1 0 1 1 *'
  push:
    branches: ["jekyll"]

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: "${{ secrets.GITHUB_TOKEN }}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        id: lint
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          FILTER_REGEX_EXCLUDE: .*(vendor|\.old|\.vscode|\.idea/).*

  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/gems
          key: ${{ runner.os }}-build-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: DavidS/jekyll-deploy@main
        env:
          JEKYLL_ENV: production
          GH_PAGES_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
        with:
          source-dir: "./src/"